Contact Form Designs/contact.html

I hope you all enjoy it - html

a simple contact form - html+css

---

Responsive Calculator Designs/BMDesign/app.css
Responsive Calculator Designs/BMDesign/index.html

Responsive calculator design added.

responsive calculator design added

---

Basic Website Designs/Contact Page/contactpage.html
Basic Website Designs/Contact Page/readme.md
Basic Website Designs/Contact Page/style.css

RaavanHack

---

Calculator Designs/responsive-calculator/index.html

i am adding style in calculator page.

add style calculator

---

Log In Form Designs/login-form-animated/index.html
Log In Form Designs/login-form-animated/style.css

I have added a simple animated login form created with HTML and CSS.

Added animated login form to Log In Form Designs folder

---

Calculator Designs/simple-responsive-calculator/README.md
Calculator Designs/simple-responsive-calculator/index.html
Calculator Designs/simple-responsive-calculator/styles.css

This is a simple responsive calculator using only HTML and CSS. Flexbox is used.

Files created and added content

---

Landing Page Designs/personalized-landing-page/readme.md

Thank you so much for merging my PR :)

Added Readme.MD to personalized-landing-page

---

Game Designs/git-game/index.html
Game Designs/git-game/readme.md

Added Git Game

---

Sign Up Form Designs/Signup form with landing page/index.html
Sign Up Form Designs/Signup form with landing page/readme.md

A simple sign up form which contains field like AADHAR ID, first_name, last_name, password and also includes a verification modal

Added Sign up form with landing page

---

Game Designs/Dollgame/dollgame.css
Game Designs/Dollgame/dollgame.html
Game Designs/Dollgame/readme.md

Done Doll-game in html, Please review it .

Doll-game using html and css'

---

Game Designs/rock-paper-scissor/index.html
Game Designs/rock-paper-scissor/readme.md

Just made a simple Rock Paper Scissor game with Javascript.

Rock Paper Scissor Game added

---

Log In Form Designs/login-form-minimal/index.html
Log In Form Designs/login-form-minimal/readme.md

Made a simple looking login form within the index.html file.

Minimal Login Form

---

Log In Form Designs/login_pure_css/login.html
Log In Form Designs/login_pure_css/readme.md
Log In Form Designs/login_pure_css/style.css
Sign Up Form Designs/signup_form/fonts.css
Sign Up Form Designs/signup_form/form.html
Sign Up Form Designs/signup_form/readme.md
Sign Up Form Designs/signup_form/style.css
Sign Up Form Designs/signup_form/styleform.css

Login and signup pages crafted with HTML and CSS.

Added a login page and a signup page sample.

---

Basic Website Designs/Restaurant-Website/README.md
Basic Website Designs/Restaurant-Website/gallery.html
Basic Website Designs/Restaurant-Website/index.html
Basic Website Designs/Restaurant-Website/menu.html
Basic Website Designs/Restaurant-Website/our-story.html
Basic Website Designs/Restaurant-Website/reservation.html
Basic Website Designs/Restaurant-Website/scripts/index.min.js
Basic Website Designs/Restaurant-Website/scripts/index.min.js.map
Basic Website Designs/Restaurant-Website/styles/gallery.css
Basic Website Designs/Restaurant-Website/styles/index.css
Basic Website Designs/Restaurant-Website/styles/index.processed.min.css
Basic Website Designs/Restaurant-Website/styles/index.processed.min.css.map
Basic Website Designs/Restaurant-Website/styles/menu.css
Basic Website Designs/Restaurant-Website/styles/our-story.css
Basic Website Designs/Restaurant-Website/styles/reservation.css

The website is made using HTML, CSS and Bootstrap. It is decently responsive.
Website has following pages:
1. Landing Page
2. Menu
3. Make a Reservation page
4. About Us Page
5. Gallery Page

Added a restaurant website

---

Sign Up Form Designs/signup-form-minimal/index.html
Sign Up Form Designs/signup-form-minimal/readme.md

Based on my minimal sign-in form, I just made the sign-up form.

Minimal sign-up form

---

Game Designs/breakout-game/index.html
Game Designs/breakout-game/main.css
Game Designs/breakout-game/main.js

Canvas Breakout Game. Control the platform with keys :) 
for : https://github.com/ShravanMeena/DevHelpBox/issues/65 
Looks like this !

Canvas game

---

Game Designs/colour-mixer-game/index.html
Game Designs/colour-mixer-game/readme.md
Game Designs/colour-mixer-game/script.js
Game Designs/colour-mixer-game/style.css

Added a simple game to teach the concept of mixing primary colours.

Add Colour Mixer Game

---

Log In Form Designs/Login Form HTML,CSS/index.html
Log In Form Designs/Login Form HTML,CSS/main.css

open source code html and css, login form

Login Form HTML with CSS

---

Contact Form Designs/Contactus/index.html
Sign Up Form Designs/SignUp form design UI/assets/css/style.css
Sign Up Form Designs/SignUp form design UI/assets/js/script.js
Sign Up Form Designs/SignUp form design UI/login.html

basic contact us page

---

Log In Form Designs/animated loginForm/assets/css/style.css
Log In Form Designs/animated loginForm/assets/js/script.js
Log In Form Designs/animated loginForm/login.html

add animated input field using core css and js

Ui login form design

---

Game Designs/WordsGoLeft/README.md
Game Designs/WordsGoLeft/index.html
Game Designs/WordsGoLeft/script.js

Add the typing game "WordsGoLeft" to the "Game Designs" folder.

Typing Game: WordsGoLeft added

---

Calculator Designs/firstCalculator/index.html
Calculator Designs/firstCalculator/readme.md
Calculator Designs/firstCalculator/script.js
Calculator Designs/firstCalculator/styles.css

I have created a responsive calculator just by using CSS, HTML & javascript. This is the first time I have worked in JS. It's amazing to work and looking forward to working on the same.

BasicCalculator_design

---

Contact Form Designs/contactForm/contactForm.css
Contact Form Designs/contactForm/contactForm.html

Added a completed contact form

Contact form

---

Basic Website Designs/.vscode/settings.json
Basic Website Designs/home.html

I add a page for my exercise and hacktoberfest

Add Home for my exercise

---

Sign Up Form Designs/signup_form/login.css
Sign Up Form Designs/signup_form/login.html
Sign Up Form Designs/signup_form/login.js
Sign Up Form Designs/work-signup-form/login.css
Sign Up Form Designs/work-signup-form/login.html
Sign Up Form Designs/work-signup-form/login.js
Sign Up Form Designs/work-signup-form/readme.md

Created a responsive signup form

Signup form

---

Portfolio Designs/portfolio/index.html
Sign Up Form Designs/HTML-pattern-validation/index.html

Change some files with add the class in tags like (label, input and button)

Add (class) in div

---

interactive buttons/colors.css
interactive buttons/debug.log
interactive buttons/layout.html

This is a simple example of how to make interactive buttons.

code for interactive buttons

---

Sign Up Form Designs/Bootstrap4-Simple-SignUp/index.html
Sign Up Form Designs/Bootstrap4-Simple-SignUp/main.css

New Bootstrap Sign Up Design
